server:
  port: 9001

spring:
  zipkin:
    base-url: http://localhost:9411/zipkin/
  application:
    name: user-service

eureka:
  instance:
    hostname: localhost

management:
    tracing:
    sampling:
      probability: 1.0